### ISSUE TITLE
Linkedin Issue

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#153]
This error occurs when upgrading with linkedin: 

`Fatal error: Uncaught Error: Class 'LinkedIn\Client' not found in /home2/uriahs/public_html/wp1/wp-content/plugins/tweet-old-post/includes/admin/services/class-rop-linkedin-service.php:131 Stack trace: #0 /home2/uriahs/public_html/wp1/wp-content/plugins/tweet-old-post/includes/admin/services/class-rop-linkedin-service.php(113): Rop_Linkedin_Service->set_api('78mohe288jxypo', 'VO8Xn8fNohJ5NWM...') #1 /home2/uriahs/public_html/wp1/wp-content/plugins/tweet-old-post/includes/admin/services/class-rop-linkedin-service.php(198): Rop_Linkedin_Service->get_api('78mohe288jxypo', 'VO8Xn8fNohJ5NWM...') #2 /home2/uriahs/public_html/wp1/wp-content/plugins/tweet-old-post/includes/admin/helpers/class-rop-db-upgrade.php(144): Rop_Linkedin_Service->authenticate(Array) #3 /home2/uriahs/public_html/wp1/wp-content/plugins/tweet-old-post/includes/admin/helpers/class-rop-db-upgrade.php(86): Rop_Db_Upgrade->migrate_accounts() #4 /home2/uriahs/public_html/wp1/wp-content/plugins/tweet-old-post/includes/class-rop.php(197): Rop_Db_Upgrade->do_upgrad in /home2/uriahs/public_html/wp1/wp-content/plugins/tweet-old-post/includes/admin/services/class-rop-linkedin-service.php on line 131`

@selul

**Comment by selul** [comment]
thanks @UVLabs it's patched in the latest one.
